using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using NUnit.Framework;
using TestStandMCP.Services;

namespace TestStandMCP.IntegrationTests.TestData;

/// <summary>
/// Builds <c>TestData.seq</c>.
///
/// One sequence per step-type category is created in the Main step group.
/// Each step receives a descriptive name and a comment.
/// After building every sequence the names and comments are read back and
/// asserted to prove the complete write→save→read round-trip.
///
/// The Main sequence receives a <c>SequenceCall</c> step for every other
/// sequence in the file.
/// </summary>
[TestFixture]
[Category("TestData")]
public class TestDataBuilderTests
{
    // ── Path ──────────────────────────────────────────────────────────────────
    private static readonly string SeqFilePath = Path.GetFullPath(
        Path.Combine(
            TestContext.CurrentContext.TestDirectory,
            @"..\..\..\..\"   // Test\TestExecution → project root
            + "TestData.seq"));

    // Use the assembly-level shared service — avoids per-fixture connect/disconnect
    // which causes COM STA/MTA finalizer crashes when creating multiple engine instances.
    private ITestStandService _ts => AssemblySetup.Ts;

    // ── Internal helpers ──────────────────────────────────────────────────────

    /// <summary>Tuple that pairs a step name with its expected type and comment.</summary>
    private sealed class StepDef
    {
        public string Type    { get; }
        public string Name    { get; }
        public string Comment { get; }
        public StepDef(string type, string name, string comment)
        { Type = type; Name = name; Comment = comment; }
    }

    private async Task BuildSequenceAsync(string seqName, IEnumerable<StepDef> steps)
    {
        await _ts.InsertSequenceAsync(SeqFilePath, seqName);
        foreach (var s in steps)
        {
            await _ts.InsertStepAsync(SeqFilePath, seqName, "Main", s.Type, s.Name);
            await _ts.SetStepCommentAsync(SeqFilePath, seqName, "Main", s.Name, s.Comment);
        }
    }

    private async Task VerifySequenceAsync(string seqName, IEnumerable<StepDef> expected)
    {
        // Re-open the saved file to confirm persistence
        await _ts.OpenSequenceFileAsync(SeqFilePath);
        var steps = await _ts.GetStepsAsync(SeqFilePath, seqName);

        foreach (var exp in expected)
        {
            var actual = steps.FirstOrDefault(s => s.Name == exp.Name);
            Assert.That(actual,             Is.Not.Null,
                $"[{seqName}] Step '{exp.Name}' not found after save+reload");
            Assert.That(actual!.StepType,   Is.EqualTo(exp.Type),
                $"[{seqName}] '{exp.Name}' — wrong step type");
            Assert.That(actual.Description, Is.EqualTo(exp.Comment),
                $"[{seqName}] '{exp.Name}' — comment did not round-trip");
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // T E S T S
    // ─────────────────────────────────────────────────────────────────────────

    [Test, Order(0)]
    public async Task Step00_CreateSequenceFile()
    {
        // Close ALL currently loaded sequence files that match our path so that
        // the TestStand engine releases any file lock from a previous run.
        try
        {
            var loaded = await _ts.GetLoadedSequenceFilesAsync();
            foreach (var f in loaded)
                if (string.Equals(f.FilePath, SeqFilePath, StringComparison.OrdinalIgnoreCase))
                    try { await _ts.CloseSequenceFileAsync(f.FilePath); } catch { }
        }
        catch { }

        // Delete old file so we always start clean
        if (File.Exists(SeqFilePath))
        {
            // Small retry loop in case the engine needs a moment to release the handle
            for (int i = 0; i < 5; i++)
            {
                try { File.Delete(SeqFilePath); break; }
                catch { System.Threading.Thread.Sleep(300); }
            }
        }

        await _ts.CreateSequenceFileAsync(SeqFilePath);
        await _ts.SetFilePropertiesAsync(SeqFilePath,
            comment: "TestData — one sequence per TestStand step-type category. " +
                     "Auto-generated by TestDataBuilderTests.",
            version: "1.0.0");

        Assert.That(File.Exists(SeqFilePath), Is.True, "Sequence file must be written to disk");
        TestContext.WriteLine($"Created: {SeqFilePath}");
    }

    // ── Statement ─────────────────────────────────────────────────────────────

    [Test, Order(1)]
    public async Task Step01_Build_Seq_Statement()
    {
        const string seqName = "Seq_Statement";
        var defs = new[]
        {
            new StepDef("Statement", "Stmt_InitVariables",
                "Initialises all local variables to their default values."),
            new StepDef("Statement", "Stmt_CalculateResult",
                "Computes the final test result from raw measurements."),
            new StepDef("Statement", "Stmt_LogTimestamp",
                "Writes the current timestamp into the test log."),
        };

        await BuildSequenceAsync(seqName, defs);
        await _ts.SetStepExpressionAsync(SeqFilePath, seqName, "Main",
            "Stmt_InitVariables", "Locals.count = 0");
        await _ts.SetStepExpressionAsync(SeqFilePath, seqName, "Main",
            "Stmt_CalculateResult", "Locals.result = Locals.raw * Locals.scaleFactor");
        await _ts.SaveSequenceFileAsync(SeqFilePath);
        await VerifySequenceAsync(seqName, defs);
    }

    // ── Action ────────────────────────────────────────────────────────────────

    [Test, Order(2)]
    public async Task Step02_Build_Seq_Action()
    {
        const string seqName = "Seq_Action";
        var defs = new[]
        {
            new StepDef("Action", "Act_PowerOnDevice",
                "Applies power to the device under test."),
            new StepDef("Action", "Act_PowerOffDevice",
                "Removes power from the device under test."),
            new StepDef("Action", "Act_ResetDevice",
                "Issues a hardware reset to the device under test."),
        };
        await BuildSequenceAsync(seqName, defs);
        await _ts.SaveSequenceFileAsync(SeqFilePath);
        await VerifySequenceAsync(seqName, defs);
    }

    // ── MessagePopup ──────────────────────────────────────────────────────────

    [Test, Order(3)]
    public async Task Step03_Build_Seq_MessagePopup()
    {
        const string seqName = "Seq_MessagePopup";
        var defs = new[]
        {
            new StepDef("MessagePopup", "Msg_ConnectDUT",
                "Prompts the operator to connect the device under test."),
            new StepDef("MessagePopup", "Msg_DisconnectDUT",
                "Prompts the operator to remove the device under test."),
            new StepDef("MessagePopup", "Msg_ConfirmCalibration",
                "Asks the operator to confirm that calibration is complete."),
        };
        await BuildSequenceAsync(seqName, defs);
        await _ts.SaveSequenceFileAsync(SeqFilePath);
        await VerifySequenceAsync(seqName, defs);
    }

    // ── CallExecutable ────────────────────────────────────────────────────────

    [Test, Order(4)]
    public async Task Step04_Build_Seq_CallExecutable()
    {
        const string seqName = "Seq_CallExecutable";
        var defs = new[]
        {
            new StepDef("CallExecutable", "Exec_RunDiagnosticTool",
                "Launches the external diagnostic utility."),
            new StepDef("CallExecutable", "Exec_OpenReportViewer",
                "Opens the HTML report in the default browser."),
        };
        await BuildSequenceAsync(seqName, defs);
        await _ts.SaveSequenceFileAsync(SeqFilePath);
        await VerifySequenceAsync(seqName, defs);
    }

    // ── SequenceCall ──────────────────────────────────────────────────────────

    [Test, Order(5)]
    public async Task Step05_Build_Seq_SequenceCall()
    {
        const string seqName = "Seq_SequenceCall";
        var defs = new[]
        {
            new StepDef("SequenceCall", "Call_PowerOnSubSeq",
                "Calls the power-on sub-sequence."),
            new StepDef("SequenceCall", "Call_CleanupSubSeq",
                "Calls the cleanup sub-sequence."),
        };
        await BuildSequenceAsync(seqName, defs);
        await _ts.SaveSequenceFileAsync(SeqFilePath);
        await VerifySequenceAsync(seqName, defs);
    }

    // ── NumericLimitTest ──────────────────────────────────────────────────────

    [Test, Order(6)]
    public async Task Step06_Build_Seq_NumericLimitTest()
    {
        const string seqName = "Seq_NumericLimitTest";
        var defs = new[]
        {
            new StepDef("NumericLimitTest", "Num_SupplyVoltage_5V",
                "Measures the 5 V supply rail and checks it is within ±5 %."),
            new StepDef("NumericLimitTest", "Num_SupplyVoltage_3V3",
                "Measures the 3.3 V supply rail and checks it is within ±5 %."),
            new StepDef("NumericLimitTest", "Num_SupplyCurrent_Idle",
                "Measures the idle current draw and checks it is below 200 mA."),
        };
        await BuildSequenceAsync(seqName, defs);
        await _ts.SetNumericLimitsAsync(SeqFilePath, seqName, "Main",
            "Num_SupplyVoltage_5V", 4.75, 5.25, "V", "GELE");
        await _ts.SetNumericLimitsAsync(SeqFilePath, seqName, "Main",
            "Num_SupplyVoltage_3V3", 3.135, 3.465, "V", "GELE");
        await _ts.SetNumericLimitsAsync(SeqFilePath, seqName, "Main",
            "Num_SupplyCurrent_Idle", null, 0.2, "A", "LT");
        await _ts.SaveSequenceFileAsync(SeqFilePath);
        await VerifySequenceAsync(seqName, defs);
    }

    // ── StringValueTest ───────────────────────────────────────────────────────

    [Test, Order(7)]
    public async Task Step07_Build_Seq_StringValueTest()
    {
        const string seqName = "Seq_StringValueTest";
        var defs = new[]
        {
            new StepDef("StringValueTest", "Str_FirmwareVersion",
                "Verifies the firmware version string matches the expected release tag."),
            new StepDef("StringValueTest", "Str_ModelIdentifier",
                "Checks that the model identifier string is correct."),
            new StepDef("StringValueTest", "Str_SerialNumberFormat",
                "Validates the serial number matches the expected 12-character format."),
        };
        await BuildSequenceAsync(seqName, defs);
        await _ts.SaveSequenceFileAsync(SeqFilePath);
        await VerifySequenceAsync(seqName, defs);
    }

    // ── PassFailTest ──────────────────────────────────────────────────────────

    [Test, Order(8)]
    public async Task Step08_Build_Seq_PassFailTest()
    {
        const string seqName = "Seq_PassFailTest";
        var defs = new[]
        {
            new StepDef("PassFailTest", "PF_ConnectionStatus",
                "Checks that the device is electrically connected."),
            new StepDef("PassFailTest", "PF_SelfTestResult",
                "Evaluates the device self-test result as pass or fail."),
            new StepDef("PassFailTest", "PF_MemoryIntegrity",
                "Checks that no memory errors were detected during POST."),
        };
        await BuildSequenceAsync(seqName, defs);
        await _ts.SaveSequenceFileAsync(SeqFilePath);
        await VerifySequenceAsync(seqName, defs);
    }

    // ── NI_MultipleNumericLimitTest ────────────────────────────────────────────

    [Test, Order(9)]
    public async Task Step09_Build_Seq_MultipleNumericLimitTest()
    {
        const string seqName = "Seq_MultipleNumericLimitTest";
        var defs = new[]
        {
            new StepDef("NI_MultipleNumericLimitTest", "Multi_AnalogInputChannels",
                "Measures all four analogue input channels in a single step."),
            new StepDef("NI_MultipleNumericLimitTest", "Multi_PowerRails",
                "Verifies all power supply rails in one measurement pass."),
        };
        await BuildSequenceAsync(seqName, defs);
        await _ts.SaveSequenceFileAsync(SeqFilePath);
        await VerifySequenceAsync(seqName, defs);
    }

    // ── NI_Flow_If / ElseIf / Else / End ─────────────────────────────────────

    [Test, Order(10)]
    public async Task Step10_Build_Seq_FlowIf()
    {
        const string seqName = "Seq_FlowIf";
        var defs = new[]
        {
            new StepDef("Statement",      "Stmt_PreIf_GetMode",
                "Reads the current operating mode into Locals.mode."),
            new StepDef("NI_Flow_If",     "If_ModeIsProduction",
                "Branches to production path when mode equals 'Production'."),
            new StepDef("Statement",      "Stmt_Production_RunFullSuite",
                "Executes the full production test suite."),
            new StepDef("NI_Flow_ElseIf", "ElseIf_ModeIsEngineering",
                "Branches to engineering path when mode equals 'Engineering'."),
            new StepDef("Statement",      "Stmt_Engineering_RunDiagnostics",
                "Runs the extended diagnostic suite."),
            new StepDef("NI_Flow_Else",   "Else_UnknownMode",
                "Handles unrecognised operating modes."),
            new StepDef("Statement",      "Stmt_UnknownMode_LogError",
                "Logs an error for the unrecognised mode."),
            new StepDef("NI_Flow_End",    "End_ModeCheck",
                "Closes the mode-selection if block."),
        };
        await BuildSequenceAsync(seqName, defs);
        await _ts.SaveSequenceFileAsync(SeqFilePath);
        await VerifySequenceAsync(seqName, defs);
    }

    // ── NI_Flow_While ─────────────────────────────────────────────────────────

    [Test, Order(11)]
    public async Task Step11_Build_Seq_FlowWhile()
    {
        const string seqName = "Seq_FlowWhile";
        var defs = new[]
        {
            new StepDef("Statement",    "Stmt_InitRetryCount",
                "Sets Locals.retries to zero before the retry loop."),
            new StepDef("NI_Flow_While","While_RetryOnFailure",
                "Repeats the measurement until the DUT passes or the retry limit is reached."),
            new StepDef("Statement",    "Stmt_TakeMeasurement",
                "Acquires a single measurement from the DUT."),
            new StepDef("Statement",    "Stmt_IncrementRetry",
                "Increments the retry counter."),
            new StepDef("NI_Flow_End",  "End_RetryLoop",
                "Closes the retry while loop."),
        };
        await BuildSequenceAsync(seqName, defs);
        await _ts.SaveSequenceFileAsync(SeqFilePath);
        await VerifySequenceAsync(seqName, defs);
    }

    // ── NI_Flow_DoWhile ───────────────────────────────────────────────────────

    [Test, Order(12)]
    public async Task Step12_Build_Seq_FlowDoWhile()
    {
        const string seqName = "Seq_FlowDoWhile";
        var defs = new[]
        {
            new StepDef("NI_Flow_DoWhile","DoWhile_PollReady",
                "Polls the device-ready flag at least once before checking the condition."),
            new StepDef("Statement",      "Stmt_ReadReadyFlag",
                "Reads the hardware ready flag into Locals.deviceReady."),
            new StepDef("NI_Flow_End",    "End_PollReady",
                "Closes the do-while poll loop."),
        };
        await BuildSequenceAsync(seqName, defs);
        await _ts.SaveSequenceFileAsync(SeqFilePath);
        await VerifySequenceAsync(seqName, defs);
    }

    // ── NI_Flow_For ───────────────────────────────────────────────────────────

    [Test, Order(13)]
    public async Task Step13_Build_Seq_FlowFor()
    {
        const string seqName = "Seq_FlowFor";
        var defs = new[]
        {
            new StepDef("NI_Flow_For",  "For_ChannelScan",
                "Iterates over each of the 8 analogue input channels."),
            new StepDef("Statement",    "Stmt_AcquireChannel",
                "Acquires the analogue value for the current channel index."),
            new StepDef("Statement",    "Stmt_ValidateChannel",
                "Checks the acquired value against the channel specification."),
            new StepDef("NI_Flow_End",  "End_ChannelScan",
                "Closes the channel-scan for loop."),
        };
        await BuildSequenceAsync(seqName, defs);
        await _ts.SetStepLoopAsync(SeqFilePath, seqName, "Main", "For_ChannelScan",
            "For",
            initExpr:  "Locals.ch = 0",
            whileExpr: "Locals.ch < 8",
            incExpr:   "Locals.ch = Locals.ch + 1");
        await _ts.SaveSequenceFileAsync(SeqFilePath);
        await VerifySequenceAsync(seqName, defs);
    }

    // ── NI_Flow_ForEach ───────────────────────────────────────────────────────

    [Test, Order(14)]
    public async Task Step14_Build_Seq_FlowForEach()
    {
        const string seqName = "Seq_FlowForEach";
        var defs = new[]
        {
            new StepDef("NI_Flow_ForEach","ForEach_TestCases",
                "Iterates over every test-case record in the test-case array."),
            new StepDef("Statement",      "Stmt_ExecuteTestCase",
                "Runs the individual test case and stores the result."),
            new StepDef("NI_Flow_End",    "End_TestCases",
                "Closes the test-case for-each loop."),
        };
        await BuildSequenceAsync(seqName, defs);
        await _ts.SaveSequenceFileAsync(SeqFilePath);
        await VerifySequenceAsync(seqName, defs);
    }

    // ── NI_Flow_Select / Case ─────────────────────────────────────────────────

    [Test, Order(15)]
    public async Task Step15_Build_Seq_FlowSelect()
    {
        const string seqName = "Seq_FlowSelect";
        var defs = new[]
        {
            new StepDef("Statement",    "Stmt_DetermineVariant",
                "Reads the product variant code from the DUT."),
            new StepDef("NI_Flow_Select","Select_ProductVariant",
                "Routes execution to the correct variant-specific test path."),
            new StepDef("NI_Flow_Case", "Case_VariantA",
                "Test path for product variant A."),
            new StepDef("Statement",    "Stmt_TestVariantA",
                "Executes the variant-A specific measurements."),
            new StepDef("NI_Flow_End",  "End_CaseVariantA",
                "Closes the variant-A case block (each Case needs its own End)."),
            new StepDef("NI_Flow_Case", "Case_VariantB",
                "Test path for product variant B."),
            new StepDef("Statement",    "Stmt_TestVariantB",
                "Executes the variant-B specific measurements."),
            new StepDef("NI_Flow_End",  "End_CaseVariantB",
                "Closes the variant-B case block."),
            new StepDef("NI_Flow_Case", "Case_VariantC",
                "Test path for product variant C."),
            new StepDef("Statement",    "Stmt_TestVariantC",
                "Executes the variant-C specific measurements."),
            new StepDef("NI_Flow_End",  "End_CaseVariantC",
                "Closes the variant-C case block."),
            new StepDef("NI_Flow_End",  "End_VariantSelect",
                "Closes the product-variant select block."),
        };
        await BuildSequenceAsync(seqName, defs);
        await _ts.SaveSequenceFileAsync(SeqFilePath);
        await VerifySequenceAsync(seqName, defs);
    }

    // ── NI_Flow_Break / NI_Flow_Continue ─────────────────────────────────────

    [Test, Order(16)]
    public async Task Step16_Build_Seq_FlowBreakContinue()
    {
        const string seqName = "Seq_FlowBreakContinue";
        var defs = new[]
        {
            new StepDef("Statement",       "Stmt_InitLoop",
                "Initialises loop counter before break/continue demo loop."),
            new StepDef("NI_Flow_While",   "While_BreakContDemo",
                "Outer loop that demonstrates both break and continue."),
            new StepDef("NI_Flow_If",      "If_ShouldBreak",
                "Checks if the exit condition is met; breaks the loop if so."),
            new StepDef("NI_Flow_Break",   "Break_ExitLoop",
                "Exits the outer loop immediately."),
            new StepDef("NI_Flow_End",     "End_IfBreak",
                "Closes the break-condition if block."),
            new StepDef("NI_Flow_If",      "If_ShouldSkip",
                "Checks if the current iteration should be skipped."),
            new StepDef("NI_Flow_Continue","Continue_SkipIteration",
                "Skips the remainder of the loop body and advances to the next iteration."),
            new StepDef("NI_Flow_End",     "End_IfSkip",
                "Closes the continue-condition if block."),
            new StepDef("Statement",       "Stmt_LoopBody",
                "Main loop body — executes when neither break nor continue fired."),
            new StepDef("NI_Flow_End",     "End_BreakContDemo",
                "Closes the break/continue demo while loop."),
        };
        await BuildSequenceAsync(seqName, defs);
        await _ts.SaveSequenceFileAsync(SeqFilePath);
        await VerifySequenceAsync(seqName, defs);
    }

    // ── MainSequence — SequenceCall steps to every sequence above ─────────────

    [Test, Order(17)]
    public async Task Step17_Build_MainSequence_WithAllSubsequenceCalls()
    {
        // All sequences created by previous steps
        var subSequences = new[]
        {
            ("Seq_Statement",               "Call_Statement",
             "Runs all Statement step examples."),
            ("Seq_Action",                  "Call_Action",
             "Runs all Action step examples."),
            ("Seq_MessagePopup",            "Call_MessagePopup",
             "Runs all MessagePopup step examples."),
            ("Seq_CallExecutable",          "Call_CallExecutable",
             "Runs all CallExecutable step examples."),
            ("Seq_SequenceCall",            "Call_SequenceCall",
             "Runs all SequenceCall step examples."),
            ("Seq_NumericLimitTest",        "Call_NumericLimitTest",
             "Runs all NumericLimitTest step examples."),
            ("Seq_StringValueTest",         "Call_StringValueTest",
             "Runs all StringValueTest step examples."),
            ("Seq_PassFailTest",            "Call_PassFailTest",
             "Runs all PassFailTest step examples."),
            ("Seq_MultipleNumericLimitTest","Call_MultipleNumericLimitTest",
             "Runs all NI_MultipleNumericLimitTest step examples."),
            ("Seq_FlowIf",                  "Call_FlowIf",
             "Runs the If / ElseIf / Else / End example sequence."),
            ("Seq_FlowWhile",               "Call_FlowWhile",
             "Runs the While / End example sequence."),
            ("Seq_FlowDoWhile",             "Call_FlowDoWhile",
             "Runs the DoWhile / End example sequence."),
            ("Seq_FlowFor",                 "Call_FlowFor",
             "Runs the For / End example sequence."),
            ("Seq_FlowForEach",             "Call_FlowForEach",
             "Runs the ForEach / End example sequence."),
            ("Seq_FlowSelect",              "Call_FlowSelect",
             "Runs the Select / Case / End example sequence."),
            ("Seq_FlowBreakContinue",       "Call_FlowBreakContinue",
             "Runs the Break / Continue example sequence."),
        };

        foreach (var (targetSeq, stepName, comment) in subSequences)
        {
            await _ts.InsertStepAsync(SeqFilePath, "MainSequence", "Main",
                "SequenceCall", stepName);
            await _ts.SetStepCommentAsync(SeqFilePath, "MainSequence", "Main",
                stepName, comment);
            await _ts.SetSequenceCallTargetAsync(SeqFilePath, "MainSequence", "Main",
                stepName, targetSeq);
        }

        await _ts.SaveSequenceFileAsync(SeqFilePath);

        // Verify
        await _ts.OpenSequenceFileAsync(SeqFilePath);
        var mainSteps = await _ts.GetStepsAsync(SeqFilePath, "MainSequence");

        foreach (var (_, stepName, comment) in subSequences)
        {
            var s = mainSteps.FirstOrDefault(x => x.Name == stepName);
            Assert.That(s, Is.Not.Null,
                $"MainSequence should contain call step '{stepName}'");
            Assert.That(s!.StepType, Is.EqualTo("SequenceCall"),
                $"'{stepName}' should be a SequenceCall step");
            Assert.That(s.Description, Is.EqualTo(comment),
                $"Comment for '{stepName}' did not round-trip");
        }

        TestContext.WriteLine($"TestData.seq saved to: {SeqFilePath}");
        TestContext.WriteLine($"  MainSequence call steps: {mainSteps.Count}");
    }
}
